---
language: ruby
release: 1.0.6
services:
- mysql
- postgresql
rvm:
- 1.9.3
- 2.0.0
- 2.2.4
env:
- REDMINE_VER=2.3.3 DB=postgresql
- REDMINE_VER=2.5.1 DB=postgresql
- REDMINE_VER=3.0.7 DB=postgresql
- REDMINE_VER=3.1.4 DB=postgresql
- REDMINE_VER=3.2.1 DB=postgresql
matrix:
matrix:
  allow_failures:
  - rvm: jruby-18mode
  - rvm: jruby-19mode
  exclude:
  - rvm: 1.9.3
    env: REDMINE_VER=3.0.7 DB=postgresql
  - rvm: 1.9.3
    env: REDMINE_VER=3.1.4 DB=postgresql
  - rvm: 1.9.3
    env: REDMINE_VER=3.2.1 DB=postgresql
  - rvm: 2.0.0
    env: REDMINE_VER=3.0.7 DB=postgresql
  - rvm: 2.0.0
    env: REDMINE_VER=3.1.4 DB=postgresql
  - rvm: 2.0.0
    env: REDMINE_VER=3.2.1 DB=postgresql
  - rvm: 2.2.4
    env: REDMINE_VER=2.5.1 DB=postgresql
  - rvm: 2.2.4
    env: REDMINE_VER=2.3.3 DB=postgresql

install: echo skip bundle install
before_script:
- sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'DROP DATABASE IF EXISTS scrum2b;'
  -U postgres; fi"
- sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'create database scrum2b;' -U
  postgres; fi"
- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS scrum2b;';
  fi"
script:
- export WORKSPACE=`pwd`/workspace
- export PATH_TO_SCRUM2B=`pwd`
- export PATH_TO_REDMINE=$WORKSPACE/redmine
- mkdir $WORKSPACE
- cp config/database.yml.travis $WORKSPACE/database.yml
- bash -x ./redmine_install.sh -r || exit 1
- bash -x ./redmine_install.sh -i || exit 1
- bash -x ./redmine_install.sh -u || exit 1
