# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
get  's2b_issues/get_data' => 's2b_issues#get_data'
post 's2b_issues/get_data' => 's2b_issues#get_data'
get  's2b_issues/destroy' => 's2b_issues#destroy'
post 's2b_issues/destroy' => 's2b_issues#destroy'
get  's2b_issues/update' => 's2b_issues#update'
post 's2b_issues/update' => 's2b_issues#update'
get  's2b_issues/update_status' => 's2b_issues#update_status'
post 's2b_issues/update_status' => 's2b_issues#update_status'
get  's2b_issues/update_version' => 's2b_issues#update_version'
post 's2b_issues/update_version' => 's2b_issues#update_version'
get  's2b_issues/update_progress' => 's2b_issues#update_progress'
post 's2b_issues/update_progress' => 's2b_issues#update_progress'
post 's2b_issues/get_issues_version' => 's2b_issues#get_issues_version'
get  's2b_issues/get_issues_version' => 's2b_issues#get_issues_version'
post 's2b_issues/create' => 's2b_issues#create'
post 's2b_issues/index' => 's2b_issues#index'
get  's2b_issues/index' => 's2b_issues#index'
post 's2b_issues/destroy_many' => 's2b_issues#destroy_many'
post 's2b_issues/change_version_issues' => 's2b_issues#change_version_issues'
post 's2b_issues/change_status_issues' => 's2b_issues#change_status_issues'

post 's2b_files/index' => 's2b_files#index'
post 's2b_files/destroy' => 's2b_files#destroy'
post 's2b_files/upload' => 's2b_files#upload'
get 's2b_files/index' => 's2b_files#index'
get 's2b_files/destroy' => 's2b_files#destroy'
get 's2b_files/upload' => 's2b_files#upload'

post 's2b_comments/index' => 's2b_comments#index'
post 's2b_comments/destroy' => 's2b_comments#destroy'
post 's2b_comments/edit' => 's2b_comments#edit'
post 's2b_comments/create' => 's2b_comments#create'
get 's2b_comments/index' => 's2b_comments#index'
get 's2b_comments/destroy' => 's2b_comments#destroy'
get 's2b_comments/edit' => 's2b_comments#edit'
get 's2b_comments/create' => 's2b_comments#create'